"""Edit test_post_limits table

Revision ID: 12693cc75615
Revises: 2b70fe4b0f56
Create Date: 2025-06-01 19:54:43.575651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12693cc75615'
down_revision: Union[str, None] = '2b70fe4b0f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_test_post_limits_user_created', 'test_post_limits', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_test_post_limits_user_date', 'test_post_limits', ['user_id', 'test_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_test_post_limits_user_date', table_name='test_post_limits')
    op.drop_index('idx_test_post_limits_user_created', table_name='test_post_limits')
    # ### end Alembic commands ###
